### PR TITLE
D3D/Metal blit improvements

### PR DESCRIPTION
**Pull request by TheSpydog**
- [x] D3D11
  - [x] Cubemaps
  - [x] 2D Arrays
  - [x] 3D
  - [x] Source rect
  - [x] Pre-cache swapchain format pipelines (N/A since d3d11 doesn't care about formats)
- [x] D3D12
  - [x] Cubemaps
  - [x] 2D Arrays
  - [x] 3D
  - [x] Source rect
  - [x] Pre-cache swapchain format pipelines
- [x] Metal
  - [x] Cubemaps
  - [x] 2D Arrays
  - [x] 3D
  - [x] Source rect
  - [x] Pre-cache swapchain format pipelines
- [x] Add an example to demonstrate cube blits
- [x] Add an example to demonstrate array blits
- [x] Add an example to demonstrate 3D blits
- [x] Use shared blit implementation in SDL_gpu.c

### CODE REVIEW

**Comment by flibitijibibo** [comment]
We may be able to move the HLSL to something like `d3dcommon`, with the backends having their own .bat to use the right compiler and defines.

**Comment by flibitijibibo** [comment]
I believe the latest commit makes this a fix for #153 as well as #84, right? I guess we still need a cache for indirect signatures though.

**Review by flibitijibibo — APPROVED** [review]
Current revision is definitely an improvement! Once CI and the example are happy this can be pushed to both gpu_next and gpu.

**Review by flibitijibibo — APPROVED** [review]
Latest is still good. Do we have any specs for formats that _aren't_ allowed necessarily? Since we do it via draws I assume this only matters for Vulkan.

**Review by thatcosmonaut — APPROVED** [review]

**Pull request merged**
