### PR TITLE
gpu: Add instanceCount parameter to SDL_GpuDrawPrimitives()

### PR DESCRIPTION
**Pull request by Akaricchi**
Partially fixes https://github.com/thatcosmonaut/SDL/issues/231

### CODE REVIEW

**Review by flibitijibibo — APPROVED** [review]
Should be okay if CI is happy

**Comment by thatcosmonaut** [comment]
I'd really like to see an indirect variant of this and a functioning test before merging.

**Comment by Akaricchi** [comment]
The plain IndirectDrawCommand already has instancing parameters https://github.com/thatcosmonaut/SDL/blob/e099043b377b26ef4843b8e1ce28a85f3e96c2a5/include/SDL3/SDL_gpu.h#L498
```c
typedef struct SDL_GpuIndirectDrawCommand
{
    Uint32 vertexCount;   /* number of vertices to draw */
    Uint32 instanceCount; /* number of instances to draw */
    Uint32 firstVertex;   /* index of the first vertex to draw */
    Uint32 firstInstance; /* ID of the first instance to draw */
} SDL_GpuIndirectDrawCommand;
```

I'm not sure why or where do you want a test for this. The only test we have in the repo is the spinning cube, which certainly doesn't cover the entire API surface. Do you want me to add an example to the SDL_gpu_examples repo?

**Comment by Akaricchi** [comment]
The plain IndirectDrawCommand already has instancing parameters https://github.com/thatcosmonaut/SDL/blob/e099043b377b26ef4843b8e1ce28a85f3e96c2a5/include/SDL3/SDL_gpu.h#L498
```c
typedef struct SDL_GpuIndirectDrawCommand
{
    Uint32 vertexCount;   /* number of vertices to draw */
    Uint32 instanceCount; /* number of instances to draw */
    Uint32 firstVertex;   /* index of the first vertex to draw */
    Uint32 firstInstance; /* ID of the first instance to draw */
} SDL_GpuIndirectDrawCommand;
```

I'm not sure why or where do you want a test for this. The only test we have in the repo is the spinning cube, which certainly doesn't cover the entire API surface. Do you want me to add an example to the SDL_gpu_examples repo?

**Comment by flibitijibibo** [comment]
> Do you want me to add an example to the SDL_gpu_examples repo?

That's probably the way to go. We already have an instancing sample so we can just rip that off.

**Comment by flibitijibibo** [comment]
Getting this in now because the weekly rebase is going to take all day and this is _mostly_ an obvious change - we still expect an example though, so I've filed that at https://github.com/TheSpydog/SDL_gpu_examples/issues/31

**Pull request merged**
